#ifndef __MESSAGE_TYPE_H__
#define __MESSAGE_TYPE_H__

#ifndef MESSAGE_NO
#define MESSAGE_NO

#define HEARTBEAT_MESSAGE_NO	"105"
#define INNER_HEARTBEAT_MESSAGE_NO	"106"

#define REGISTER_MESSAGE_NO	"200"
#define LIVEINFO_MESSAGE_NO	"201"

#define UNICAST_MESSAGE_NO	"202"
#define UNICAST_MESSAGE_RESP_NO		"302"

#define BROADCAST_MESSAGE_NO	"203"
#define BROADCAST_MESSAGE_RESP_NO	"303"

#endif

#endif
